schema_version = 1

[upstream_state]
platform = "curseforge"
project_id = "1503381"
version = "Enigmatic Skies 1.5.0"
artifact_id = "8085819"
artifact_kind = "curseforge_file"
primary_file_name = "EnigmaticSkies-1.5.0.zip"
fetched_at = "2026-05-17T14:34:46Z"
source_archive_sha256 = "332387494cd75c1b9afd219c1dae6afb0acb7896f9f9817ba7eeba795785ded8"
