name: Modpack Validate

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    uses: TeamKugimiya/reusable-workflows/.github/workflows/Modpack-Validate.yml@v1
    with:
      strict: true
    secrets: inherit
